name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
no-changes-template: "* No changes"

categories:
  - title: Enhancements
    label: enhancement
  - title: Bug Fixes
    label: bug

template: |
  ## Changes

  $CHANGES
