daysUntilStale: 90  # Number of days of inactivity before an issue becomes stale
daysUntilClose: 14  # Number of days of inactivity before a stale issue is closed
exemptLabels:       # Issues with these labels will never be considered stale
  - pinned
  - security
staleLabel: wontfix # Label to use when marking an issue as stale
markComment: >
  This issue has been automatically marked as stale because it has not had any activity in the past 90 days. It will be
  closed if no further activity occurs 14 days from now. Thank you for your contributions.
closeComment: Closing stale issue due to no activity for the past 14 days.
